apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-live
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mindtastic/deployments
    targetRevision: HEAD
    path: external-dns
    helm:
      releaseName: external-dns
      valueFiles:
      - values-common.yaml
      - values-live.yaml    
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns # Namespace for your application
  syncPolicy:
      syncOptions:
        - CreateNamespace=true
