linkerd-viz: {}
  # grafana:
  #   enabled: false
  # prometheus:
  #   enabled: false

linkerd-jaeger:
  installNamespace: false
  namespace: linkerd-viz
  collectorSvcAddr: collector.linkerd-viz:55678
