linkerd-viz:
  grafana:
    enabled: false
  prometheus:
    enabled: false
  prometheusUrl: http://prometheus.monitoring:9090

linkerd-jaeger:
  installNamespace: false
  namespace: linkerd-viz
  webhook:
    collectorSvcAddr: collector.linkerd-viz:55678
  