linkerd-viz:
  grafana:
    enabled: false
  prometheus:
    enabled: true
    alertmanagers: "- kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093"
  jaegerUrl : https://jaeger-dev.teleport.mindtastic.lol
  grafaUrl: https://grafana-dev.teleport.mindtastic.lol

linkerd-jaeger:
  installNamespace: false
  namespace: linkerd-viz
  webhook:
    collectorSvcAddr: collector.linkerd-viz:55678
  