linkerd-viz:
  grafana:
    enabled: false
  prometheus:
    enabled: true
  jaegerUrl : "http://jaeger.linkerd-viz:16686/jaeger"
  grafaUrl: https://grafana-dev.teleport.mindtastic.lol
  dashboard:
    enforcedHostRegexp: ".*"

linkerd-jaeger:
  installNamespace: false
  namespace: linkerd-viz
  webhook:
    collectorSvcAddr: collector.linkerd-viz:55678
  