linkerd-viz:
  grafana:
    enabled: false
  prometheus:
    enabled: false
  prometheusUrl: http://kube-prometheus-stack-prometheus.monitoring:9090
  jaegerUrl : https://jaeger-dev.teleport.mindtastic.lol
  grafaUrl: https://grafana-dev.teleport.mindtastic.lol

linkerd-jaeger:
  installNamespace: false
  namespace: linkerd-viz
  webhook:
    collectorSvcAddr: collector.linkerd-viz:55678
  