{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "traefik.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "traefik.name" . }}
    helm.sh/chart: {{ template "traefik.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "traefik.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    {{if .Values.networkPolicy.ingress.enabled -}}
    - Ingress
    {{- end -}}
    {{- if .Values.networkPolicy.egress.enabled -}}
    - Egress
    {{- end -}}
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
  {{- toYaml .Values.networkPolicy.ingress.spec | nindent 2 }}
  {{- end }}
  {{if .Values.networkPolicy.egress.enabled }}
  egress:
  {{- toYaml .Values.networkPolicy.egress.spec | nindent 2 }}
  {{- end }}
{{- end }}