image:
  repository: ghcr.io/mindtastic/user-service
  pullPolicy: IfNotPresent
  tag: "dev-d80870e08a0db86bea794b8661c2150395a9c203"

accessRule:
  matchPath: "https://users.api.dev.mindtastic.lol/user/<.+>"
  matchMethods: ["GET","PUT","DELETE","POST"]
  kratosCheckSessionURL: http://kratos-public.kratos.svc.cluster.local/sessions/whoami
  kodaHydratorURL: http://koda.koda.svc.cluster.local:4133/

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: auth@file
  hosts:
    - host: "users.api.dev.mindtastic.lol"
      paths:
        - path: /
          pathType: Prefix
  tls: []
